# -*- coding: utf-8 -*-
"""RCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HbSvNHwclYtInhc9zjJW-4SoSI32nrJX
"""

#Load Data
traffic_raw <- read.table('/content/aadt.txt',header=FALSE)
traffic <-
  data.frame(y=traffic_raw$V1,x1=traffic_raw$V2,x2=traffic_raw$V3,x3=traffic_raw$V4, x4=traffic_raw$V5)
traffic

nrow(traffic)

#convert data type of categorical variable from character to integer
# Convert character to factor
traffic$x4 <- as.factor(traffic$x4)

# Convert factor to integer
traffic$x4 <- as.integer(traffic$x4)
traffic

# Replace 2 with 0
traffic$x4 <- ifelse(traffic$x4 == 2, 0, traffic$x4)
traffic$x4 <- as.numeric(traffic$x4)
traffic

summary(traffic)

plot(traffic)

# keep these for normalising y later
y_mean <- mean(traffic$y)
y_sd <- sd(traffic$y)
y_mean
y_sd

# Fit a multiple linear regression model.
model0 <- lm(y ~ x1+x2+x3+x4, data=traffic)

names(model0)

summary_model0 <- summary(model0)
names(summary_model0)

# Normality checking.
qqnorm(residuals(model0),ylab='Residuals')
qqline(residuals(model0))

# As we can tell from this model below, we have some evidence that the linear model is poor because the residuals do not follow a normal distribution. Next, we try the durbin-watson test.

# Using the boxcox function from the MASS package
install.packages("MASS")
library(MASS)

# Box-Cox transformation for response variable 'y'
bc <- boxcox(traffic$y ~ traffic$x1 + traffic$x2 + traffic$x3 + traffic$x4)
(lambda <- bc$x[which.max(bc$y)])

model1 <- lm(((y^lambda-1)/lambda) ~ x1+x2+x3+x4, data=traffic)

# Mentioned in google docs
model2 <- lm(((y^(1/3))) ~ log(x1)+log(x2)+log(x3)+x4, data=traffic)

model3 <- lm(((y^(1/3))) ~ log(x1)+log(x2)+x4, data=traffic)

model4 <- lm(((y^lambda-1)/lambda) ~ log(x1)+log(x2)+log(x3)+x4, data=traffic)

model5 <- lm(((y^(1/3))) ~ log(x1) +(x2)^2 +log(x3)+x4, data=traffic)

model6 <- lm(((y^(1/3))) ~ sqrt(log(x1)) + (x2) +log(x3)+x4, data=traffic)

model7 <- lm(((y^(7/25))) ~ sqrt(x1) + log(x2) + log(x3)+x4, data=traffic)

model8 <- lm(((y^(7/25))) ~ I(x1^(1/3)) + log(x2) + log(x3) +x4, data=traffic)

model9 <- lm(((y^(7/25))) ~ log(x1) + log(x2) + log(x3) +x4, data=traffic)

model10 <- lm(((y^(7/25))) ~ log(x1) + log(x2) +x4, data=traffic)

model11 <- lm(((y^(7/20))) ~ log(x1) + log(x2) + log(x3) +x4, data=traffic)

model12 <- lm(((y^(7/25))) ~ x1 + log(x2) +x4, data=traffic)

model13 <- lm(((y-y_mean)/y_sd) ~ log(x1) + log(x2) + log(x3) +x4, data=traffic)

model14 <- lm(((y-y_mean)/y_sd) ~ x1 + x2 + log(x3) +x4, data=traffic)

model15 <- lm(((y-y_mean)/y_sd) ~ x1 + x2 + x3 +x4, data=traffic)

summary(model0)

summary(model1)

summary(model2)

summary(model3)

summary(model4)

summary(model5)

summary(model6)

summary(model7)

summary(model8)

summary(model9)

summary(model10)

install.packages("lmtest")

summary(model12)

summary(model13)

summary(model14)

summary(model15)

# Durbin-Watson test for model0

library(lmtest)
dwtest(y ~ x1+x2+x3+x4, data=traffic)

# As we can see from the Durbin-Watson test, we obtain a small p-value, and can reject the null hypothesis of no autocorrelation.
# This means that the residuals are dependent, which makes this model poor. Hence, we try the boxcox model instead.

#NOTE A BETTER VALUE IS CLOSER TO 2

# Durbin-Watson test for model0
dwtest(model1, data=traffic)

dwtest(model2, data=traffic)

dwtest(model7, data=traffic)

dwtest(model9, data=traffic)

# Durbin-Watson test for final reduced model, model10
dwtest(model10, data=traffic)

# Normality checking for model 1
qqnorm(residuals(model1),ylab='Residuals')
qqline(residuals(model1))

# As we can see, the QQ plot shows that the residuals for the boxcox model more closely follows a normal distribution, suggesting that this model is more adequate.

# Normality checking for model 2
qqnorm(residuals(model2),ylab='Residuals')
qqline(residuals(model2))

# Normality checking for the transformed model
qqnorm(residuals(model3),ylab='Residuals')
qqline(residuals(model3))

# Normality checking for the transformed model
qqnorm(residuals(model4),ylab='Residuals')
qqline(residuals(model4))

# Normality checking for the transformed model
qqnorm(residuals(model5),ylab='Residuals')
qqline(residuals(model5))

# Normality checking for the model 6
qqnorm(residuals(model6),ylab='Residuals')
qqline(residuals(model6))

# Normality checking for model 13
qqnorm(residuals(model13),ylab='Residuals')
qqline(residuals(model13))

# Normality checking for model 14
qqnorm(residuals(model14),ylab='Residuals')
qqline(residuals(model14))

# Normality checking for model 15
qqnorm(residuals(model15),ylab='Residuals')
qqline(residuals(model15))

# Linear Model 0
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model0),ylab='Residuals',xlab='Time')
plot(fitted(model0), residuals(model0),ylab='Residuals',xlab='Fitted values')
plot(traffic$x1, residuals(model0),ylab='Residuals',xlab='X1')
plot(traffic$x2, residuals(model0),ylab='Residuals',xlab='X2')
plot(traffic$x3, residuals(model0),ylab='Residuals',xlab='X3')
plot(traffic$x4, residuals(model0),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 1
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model1),ylab='Residuals',xlab='Time')
plot(fitted(model1),residuals(model1),ylab='Residuals',xlab='Fitted values')
plot(traffic$x1,residuals(model1),ylab='Residuals',xlab='X1')
plot(traffic$x2,residuals(model1),ylab='Residuals',xlab='X2')
plot(traffic$x3,residuals(model1),ylab='Residuals',xlab='X3')
plot(traffic$x4,residuals(model1),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 2
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model2),ylab='Residuals',xlab='Time')
plot(fitted(model2),residuals(model2),ylab='Residuals',xlab='Fitted values')
plot(log(traffic$x1),residuals(model2),ylab='Residuals',xlab='log(X1)')
plot(log(traffic$x2),residuals(model2),ylab='Residuals',xlab='log(X2)')
plot(log(traffic$x3),residuals(model2),ylab='Residuals',xlab='log(X3)')
plot(traffic$x4,residuals(model2),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 3
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model3),ylab='Residuals',xlab='Time')
plot(fitted(model3),residuals(model3),ylab='Residuals',xlab='Fitted values')
plot(log(traffic$x1),residuals(model3),ylab='Residuals',xlab='X1')
plot(log(traffic$x2),residuals(model3),ylab='Residuals',xlab='X2')
plot(traffic$x4,residuals(model3),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 4
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model4),ylab='Residuals',xlab='Time')
plot(fitted(model4),residuals(model4),ylab='Residuals',xlab='Fitted values')
plot(log(traffic$x1),residuals(model4),ylab='Residuals',xlab='log(X1)')
plot(log(traffic$x2),residuals(model4),ylab='Residuals',xlab='log(X2)')
plot(log(traffic$x3),residuals(model4),ylab='Residuals',xlab='log(X3)')
plot(traffic$x4,residuals(model4),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 5
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model5),ylab='Residuals',xlab='Time')
plot(fitted(model5),residuals(model5),ylab='Residuals',xlab='Fitted values')
plot(log(traffic$x1),residuals(model5),ylab='Residuals',xlab='log(X1)')
plot((traffic$x2)^2,residuals(model5),ylab='Residuals',xlab='(X2)^2')
plot(log(traffic$x3),residuals(model5),ylab='Residuals',xlab='log(X3)')
plot(traffic$x4,residuals(model5),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 6
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model6),ylab='Residuals',xlab='Time')
plot(fitted(model6),residuals(model6),ylab='Residuals',xlab='Fitted values')
plot(sqrt(log(traffic$x1)),residuals(model6),ylab='Residuals',xlab='(log(X1))^(1/2)')
plot((traffic$x2)^2,residuals(model6),ylab='Residuals',xlab='(X2)^2')
plot(log(traffic$x3),residuals(model6),ylab='Residuals',xlab='log(X3)')
plot(traffic$x4,residuals(model6),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 7
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model7),ylab='Residuals',xlab='Time')
plot(fitted(model7),residuals(model7),ylab='Residuals',xlab='Fitted values')
plot(sqrt(traffic$x1),residuals(model7),ylab='Residuals',xlab='(X1)^(1/2)')
plot(log(traffic$x2),residuals(model7),ylab='Residuals',xlab='log(X2)')
plot(log(traffic$x3),residuals(model7),ylab='Residuals',xlab='log(X3)')
plot(traffic$x4,residuals(model7),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 8
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model8),ylab='Residuals',xlab='Time')
plot(fitted(model8),residuals(model8),ylab='Residuals',xlab='Fitted values')
plot((traffic$x1)^(1/3),residuals(model8),ylab='Residuals',xlab='X1^(1/3)')
plot(log(traffic$x2),residuals(model8),ylab='Residuals',xlab='log(X2)')
plot(log(traffic$x3),residuals(model8),ylab='Residuals',xlab='log(X3)')
plot(traffic$x4,residuals(model8),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Model 9
 par(mfrow=c(1,2))
 #we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
 #hence, the residuals against time plot may not provide informative insignts
 plot(residuals(model9),ylab='Residuals',xlab='Time')
 plot(fitted(model9),residuals(model9),ylab='Residuals',xlab='Fitted values')
 plot(log(traffic$x1),residuals(model9),ylab='Residuals',xlab='log(X1)')
 plot(log(traffic$x2),residuals(model9),ylab='Residuals',xlab='log(X2)')
 plot(log(traffic$x3),residuals(model9),ylab='Residuals',xlab='log(X3)')
 plot(traffic$x4,residuals(model9),ylab='Residuals',xlab='X4')
 par(mfrow=c(1,1))

# Model 10
 par(mfrow=c(1,2))
 #we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
 #hence, the residuals against time plot may not provide informative insignts
 plot(residuals(model10),ylab='Residuals',xlab='Time')
 plot(fitted(model10),residuals(model10),ylab='Residuals',xlab='Fitted values')
 plot(log(traffic$x1),residuals(model10),ylab='Residuals',xlab='log(X1)')
 plot(log(traffic$x2),residuals(model10),ylab='Residuals',xlab='log(X2)')
 plot(traffic$x4,residuals(model10),ylab='Residuals',xlab='X4')
 par(mfrow=c(1,1))

# Model 12
par(mfrow=c(1,2))
#we don't have specific time component in our data, and we are not sure if the data is arranged in order of observations with respect to time.
#hence, the residuals against time plot may not provide informative insignts
plot(residuals(model12),ylab='Residuals',xlab='Time')
plot(fitted(model12),residuals(model12),ylab='Residuals',xlab='Fitted values')
plot(traffic$x1,residuals(model12),ylab='Residuals',xlab='X1')
plot(log(traffic$x2),residuals(model12),ylab='Residuals',xlab='log(X2)')
plot(traffic$x4,residuals(model12),ylab='Residuals',xlab='X4')
par(mfrow=c(1,1))

# Having found an appropriate model, model9, we proceed to conduct F-tests on it to observe whether all of the predictor variables are significant.
# We first test the significance of log(x3) because we see that from summary(model9) that log(x3) has a low t-statistic or 1.022.

# CONDUCTING F-TEST FOR MODEL 9
# Basic reduced models: Checking B3 = 0
summary(model10)
anova(model10,model9)

step <- stepAIC(model9, direction = "both")
step

anova(model10, model9)

mlrs<-summary(model10)

# Prediction
con <- c(1, log(50000),log(3),0)
#creates a vector named con with five elements: 1, 50000, 3, 60, and 2
lhat <- sum(con*coef(model10))
lhat #linear prediction based on the linear regression model
y_pred <- lhat^(25/7)
y_pred
t05 <- qt(0.975,117) #a two-tailed test with a confidence level of 95%, with 117 degrees of freedom
bm <- t05*mlrs$sigma*sqrt(con%*%mlrs$cov.unscaled%*%con) #standard error
c(lhat-bm,lhat+bm)#confidence interval
c3 <- 1
bm <- t05*mlrs$sigma*sqrt(con%*%mlrs$cov.unscaled%*%con+c3)
#new standard error (bm) with constant (c3)
c(lhat-bm,lhat+bm)
con <- data.frame(x1=50000,x2=3, x4=0)
#creates a data frame named con with four variables (x1, x2, x3, x4) and sets their values
predict(model10,con,interval='confidence',level=0.95) #predict the response variable
predict(model10,con,interval='prediction',level=0.95) #prediction interval
